version: '3.4'
services:
  ethdo.avado.dappnode.eth:
    build:
      context: build
      args:
        UPSTREAM_VERSION: 1.28.5
    image: 'ethdo.avado.dappnode.eth:0.0.5'
    restart: always
    volumes:
      - 'data:/data'
    environment:
      - NETWORK=mainnet
    ports:
      - '80:80'
volumes:
  data: {}
